name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild ChromiumDecryptor.sln /p:Configuration=Release /p:Platform=x64 /t:Build /p:OutputPath=Decryptor/

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: Decryptor/ChromiumDecryptor.dll
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
